### ISSUE TITLE
fuse error

### ISSUE THREAD

**Issue by jimalad** [gitless-vcs/gitless#231]
I'm trying to use fuse to bring the baseline of my PR branch up to date with HEAD of master.

```
gl switch MyPullRequestBranch
gl fuse origin/master
git mergetool filename (to fix a conflict)
gl status (looks clean with some deletes, adds and changes)
gl commit
```

And I get this error...

```
 Some internal error occurred
   If you want to help, see http://gitless.com for info on how to report bugs and include the following information:

  0.8.8

  Traceback (most recent call last):
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\gitless\cli\gl.py", line 99, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\gitless\cli\gl_commit.py", line 67, in main
      ci = curr_b.create_commit(commit_files, msg, partials=partials)
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\gitless\core.py", line 1250, in create_commit
      msg, get_tree_and_update_index(),  # the commit tree
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\gitless\core.py", line 1222, in get_tree_and_update_index
      update()
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\gitless\core.py", line 1215, in update
      index.remove(git_f)
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\pygit2\index.py", line 175, in remove
      check_error(err, True)
    File "c:\users\user\appdata\local\programs\python\python27-32\lib\site-packages\pygit2\errors.py", line 53, in check_error
      raise IOError(message)
  IOError: index does not contain Source/SomeDirectory/AssemblyInfo.cs at stage 0
```

I can see that the file it's complaining about 'Source/SomeDirectory/AssemblyInfo.cs' has been deleted as part of the latest commit on the PR branch.

Is there a workaround I can use with just git commands to complete the fuse?

**Comment by spderosso** [comment]
try doing `gl resolve path` where `path` is the one corresponding to `AssemblyInfo.cs`---this might fix the error and you might be able to complete the fuse without switching to `git`.

If that doesn't work, you can (1) copy the files you resolved outside of the repo so that you don't loose the changes you've made and (2) abort the fuse, which will put you back to the state in which you were before you started the fuse. Then you can use `git` to pull the changes from `origin/master`, copy over the files you resolved, `git add` them to mark them as resolved and `git rebase --continue`.

Let me know if you managed to resolve the issue or if you have any other questions.
